Fix GSourceFunc removal
xfce-panel-plugin.c: In function 'xfce_panel_plugin_menu_move':
error: passing argument 1 of 'g_idle_add' from incompatible pointer type [-Werror=incompatible-pointer-types]

Fixes commit 469073d8ba52077132824d668b030cc3f1e25db5

Signed-off-by: Olaf Hering <olaf@aepfle.de>